import { nodeToType, pascalCase } from './json-schema-to-ts.ts';
import type { GenerateOptions, ResourceSchema, WPSchemaNode } from './types.ts';

const DEFAULT_BANNER = [
	'/**',
	' * Auto-generated by wp-rest-typegen. Do not edit by hand.',
	' * Regenerate with: npx wp-rest-typegen --url <site>',
	' */',
].join('\n');

/** Render one resource schema to an exported `interface`. */
export function renderInterface(resource: ResourceSchema, options: GenerateOptions): string {
	const context = options.context ?? 'view';
	const { schema } = resource;
	const props = schema.properties ?? {};
	const keys = Object.keys(props).filter((key) => {
		const ctx = props[key].context;
		return !ctx || ctx.length === 0 || ctx.includes(context);
	});

	const lines: string[] = [];
	if (schema.description) {
		lines.push(`/** ${schema.description.replace(/\*\//g, '*\\/')} */`);
	}
	lines.push(`export interface ${resource.name} {`);

	for (const key of keys) {
		const child = props[key];
		if (child.description) {
			lines.push(`\t/** ${child.description.replace(/\*\//g, '*\\/')} */`);
		}
		const optional = child.readonly === false ? '?' : '';
		const safeKey = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key);
		const type = nodeToType(child, { context, indent: '\t' });
		lines.push(`\t${safeKey}${optional}: ${type};`);
	}

	lines.push('}');
	return lines.join('\n');
}

/** Derive a resource (name + base) from a raw schema + its rest base. */
export function toResource(
	restBase: string,
	schema: WPSchemaNode,
	namespace?: string
): ResourceSchema {
	const title = schema.title || restBase;
	return { restBase, namespace, name: pascalCase(title), schema };
}

/** Render a full `.d.ts` document from a set of resources. */
export function generate(resources: ResourceSchema[], options: GenerateOptions = {}): string {
	const banner = options.banner ?? DEFAULT_BANNER;
	const blocks: string[] = [banner, ''];

	// De-dupe interface names (e.g. multiple bases mapping to `Post`).
	const seen = new Set<string>();
	for (const resource of resources) {
		let name = resource.name;
		let n = 2;
		while (seen.has(name)) name = `${resource.name}${n++}`;
		seen.add(name);
		blocks.push(renderInterface({ ...resource, name }, options));
		blocks.push('');
	}

	if (options.registry !== false && resources.length > 0) {
		// Qualify colliding bases with their namespace so registry keys stay unique.
		const baseCounts = new Map<string, number>();
		for (const r of resources) baseCounts.set(r.restBase, (baseCounts.get(r.restBase) ?? 0) + 1);
		const entries = resources.map((r) => {
			const key =
				baseCounts.get(r.restBase)! > 1 && r.namespace
					? `${r.namespace}/${r.restBase}`
					: r.restBase;
			return `\t${JSON.stringify(key)}: ${r.name};`;
		});
		blocks.push('/** Maps each REST base to its resource type. */');
		blocks.push('export interface WPRestTypes {');
		blocks.push(...entries);
		blocks.push('}');
		blocks.push('');
	}

	return blocks.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n';
}
